### ISSUE TITLE
Datum geleert und neu eingefügt bringt Fehlemeldung

### ISSUE THREAD

**Issue by Koala** [alexplusde/neues#18]
Wird das Datumsfeld über den Datumswähler geleert, kann auch ohne Datum gespeichert werden.  
Wird dann aber über den Datumwähler ein Datum gewählt, fehlt die Uhrzeit und ein Speichern ist nicht möglich. Eine Zeit muss dann händisch eingetragen werden.

Soll das so oder ist das nur bei mir so?

**Comment by Koala** [comment]
Ich sehe gerade, dass im Addon [yform_field](https://github.com/Koala/yform_field) beim Datepicker auch eine Zeit erscheinen müsste. Ist bei mir aber nicht da 🤔 

**Aus der Doku:**

![grafik](https://github.com/alexplusde/neues/assets/330686/536b6502-25b3-4091-aaa3-ad45c08e5a70)

--- 
**Was ich sehen:**
![grafik](https://github.com/alexplusde/neues/assets/330686/20d8679f-680a-4fde-8552-45678e43b515)

**Comment by alxndr-w** [comment]
Welchen Browser und welches Betriebssystem nutzt du?

**Comment by Koala** [comment]
Firefox + Linux

Falls die Browsersignatur ausgewertet wird, da steht bei mir etwas von Chrome und Windows drin.

**Comment by alxndr-w** [comment]
Der Datumspicker kommt vom Betriebssystem und daher darf der optisch anders aussehen. Was passiert denn, wenn du auf die Uhrzeit klickst, kommt dann ein Uhrzeit-Picker? 

Laut https://caniuse.com/mdn-html_elements_input_type_datetime-local unterstützt Firefox den Picker korrekt.

**Comment by Koala** [comment]
Das Aussehen ist mir wurscht, funktionieren muss es 😄 

Die einzelnen Ziffern kann ich beim Ankilcken nur markieren. Da passiert nix weiter. Nur wenn ich rechts auf das Icon gehe, öffnet sich die Auswahlansicht.

![grafik](https://github.com/alexplusde/neues/assets/330686/a8bb37af-a344-4f58-abbd-b0402d169ab1)

Auf der Seite funktioniert es aber auch nicht: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

Also scheint es ein reines Browserproblem zu sein ... 
... ok, hab grad mal Chromium gestartet und da funktioniert sowohl die Mozilla-Seite als auch die lokale Testseite mit dem AddOn.

Thema wird geschlossen.
Ist aber gut zu wissen, dass es ein reines Browserproblem ist.

**Comment by alxndr-w** [comment]
Ich finde es nicht ideal, dass das im Firefox nicht geht, setze aber bewusst auf den Standard um langfristig keine eigenen Abhängigkeiten von Javascript-Bibliotheken drin zu haben. Aber gut zu wissen! Wundert mich, dass das im Firefox nicht tut.

**Comment by Koala** [comment]
**Ergänzung**

Firefox schleppt das wohl schon ein paar Jahre unfertig mit sich rum 😮
Zum DateTimePicker-Problem gibt es auch einen Bug-Report: https://bugzilla.mozilla.org/show_bug.cgi?id=1726108
