### ISSUE TITLE
Status nicht sichtbar in Gesamtansicht

### ISSUE THREAD

**Issue by Koala** [alexplusde/neues#19]
In der Gesamtansicht der Einträge sehe ich bei mir keinen Status (Online/Offline/Entwurf).  
In der Hilfe ist die Spalte im Bild aber zu sehen.  
Was fehlt bei mir?

![grafik](https://github.com/alexplusde/neues/assets/330686/1021c11e-f397-4efb-bd2f-8e065179805d)

**Comment by alxndr-w** [comment]
Ist yform_field bei dir installiert?

**Comment by Koala** [comment]
Ja, daher kam ja auch der letzte PR für yform-field zustande.

**Comment by alxndr-w** [comment]
Das müsste umgewandelt werden in ein Feld vom Typ choice_status - weil nur dieses einwandfrei mit YOrm zusammenarbeitet.

**Comment by Koala** [comment]
Wo müsste was geändert werden?
"Status" ist bei mir Typ "choice".

![grafik](https://github.com/alexplusde/neues/assets/330686/c081064d-6a7d-42f8-b3b8-c971adcfca31)

**Comment by alxndr-w** [comment]
Variante A: Felddefinition von `status` mit dem Feldtyp Value `choice` löschen und dann neu als `status` mit dem Feldtyp Value `choice_status` hinzufügen.

Variante B: In der Datenbank, z.B. bei Adminer, den Datensatz von von `rex_neues_entry.status` in `rex_yform_field` von `choice` auf `choice_status` ändern und dann den REDAXO-Cache löschen.

**Comment by Koala** [comment]
Zusätzlich muss bei YForm Table Manager noch bei dem Status-Feld gaaanz unten, das Häckchen bei "In Liste verstecken" rausgenommen werden 😄 

![grafik](https://github.com/alexplusde/neues/assets/330686/c819a370-90a0-499b-b457-170d70d20bff)

Dann erscheint

![grafik](https://github.com/alexplusde/neues/assets/330686/aa9a6f31-13c8-40ce-845c-00fd980eee20)

Problem ist jetzt aber, wenn ich darüber den Status versuche zu ändern, sehe ich eine Abfrage
![grafik](https://github.com/alexplusde/neues/assets/330686/233ad357-e76a-49d2-b943-5bc71ca27cbe)

nach dem OK sehe ich dann nur den drehenden Kreisel, aber es passiert nichts weiter. Keine Fehlermeldung, nix.

![grafik](https://github.com/alexplusde/neues/assets/330686/028712f6-b3dd-4362-b720-8ad0b2de2abd)

**Comment by alxndr-w** [comment]
Vielen Dank fürs Testen. Ich schreib dir Mal in Slack dazu, du hast alles richtig gemacht.

**Comment by alxndr-w** [comment]
Sollte jetzt passen!
