### ISSUE TITLE
$entry->getPublishDateTime(); gibt es nirgends

### ISSUE THREAD

**Issue by Koala** [alexplusde/neues#23]
https://github.com/alexplusde/neues/blob/45e1f8bd5acd1133dce73868624e247d0b0b9cff/README.md?plain=1#L61C35-L61C35

`$entry->getPublishDateTime();` gibt es nirgends.
In `$entry->getPublishDate()` ist ja bereits alles vorhanden (Tag und Zeit).

**Comment by alxndr-w** [comment]
Ja, die README ist nicht up to date. Ich bin mir generell unschlüssig, wie ich mit Datumsangaben Add-on übergreifend verfahren will. 

Ich versuche gerade ein Hilfsskript zu programmieren, das anhand des Tablesets und der Feldtypen passende einheitliche Methoden und Doku ausspuckt.

**Comment by alxndr-w** [comment]
Wird in der kommenden Version nach 3.3.0 korrigiert sein.
