### ISSUE TITLE
'url_Label' gibt es nicht

### ISSUE THREAD

**Issue by Koala** [alexplusde/neues#24]
https://github.com/alexplusde/neues/blob/45e1f8bd5acd1133dce73868624e247d0b0b9cff/lib/neues_entry.php#L76

`echo $entry->getExternalLabel();`
Hier wird `'url_Label'` abgefragt. Das gibt es aber nicht als Spalte. Zumindest nicht in `rex_neues_entry`. 
Was soll das sein?

**Comment by alxndr-w** [comment]
Das stimmt, das ist aus einem Projekt, aus dem das Addon entstanden ist. Die Methode muss entfernt werden.

**Comment by alxndr-w** [comment]
wird mit der Version nach 3.3.0 behoben sein.
