### ISSUE TITLE
Autoren-Tabelle anlegen, automatische Erstellung eines Autoren-Profils für eingeloggte Nutzer

### ISSUE THREAD

**Issue by alxndr-w** [alexplusde/neues#25]
Diskussion aus https://github.com/alexplusde/neues/pull/22

- [x] Autoren-Tabelle
- [x] Name, Alias, E-Mail-Adresse, Benutzerprofilbild, Website
- [x] YOrm-Klasse
- [ ] Profilseite
- [ ] Für Admins eine Liste an erstellten Profilen und zugeordneten Beiträgen

/cc @Koala

**Comment by alxndr-w** [comment]
In dem Zuge könnte man über ein kleines Berechtigungsmanagement von Neues, Events und QandA nachdenken: Ob man nur eigene Einträge oder alle bearbeiten darf.

**Comment by Koala** [comment]
Mögliche Rechtevarianten/Konstellationen:
Benutzer dürfe ...
-  nur für bestimmte Kategorien etwas anlegen
- für alle Kategorien etwas anlegen aber nur ihre eigenen Beiträge bearbeiten
- Kategorien Online/Offline schalten aber nichts am Inhalt ändern

Welche Konstellationen könnte es noch geben?

**Comment by alxndr-w** [comment]
Puh, das wäre schon weiter weg von einem "kleinen" Berichtungsmanagement. Per EP kann man als Entwickler sowieso noch stärker eingreifen. Da müsste man erstmal schauen, wie das finanziert wird.
