### ISSUE TITLE
Optional: Beispielmodule/Templates

### ISSUE THREAD

**Issue by eaCe** [alexplusde/neues#48]
Beispiele für Module oder Templates installieren können.
Ich selbst bin kein Freund von SQL Dateien für sowas. Daher würde ich da eher über Fragmente und php-Dateien gehen, die können dann über REDAXO eigene Funktionen hinzugefügt werden.
Dann bleibt die Frage, ob und wie man das stylen sollte..

**Comment by alxndr-w** [comment]
Duplicate #42

**Comment by eaCe** [comment]
Sorry. Hatte das anhand des Titels nicht erkannt
